keycloak:
  enabled: false
apisix:
  image:
    debug: true
  dataPlane:
    ingress:
      enabled: true
      hostname: mp-data-service.127.0.0.1.nip.io
      extraHosts:
        - name: mp-tmf-api.127.0.0.1.nip.io
          path: /
  catchAllRoute:
    enabled: false
  routes: |-
    - uri: /.well-known/openid-configuration
      host: mp-data-service.127.0.0.1.nip.io
      upstream:
        nodes:
          verifier:3000: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /services/data-service/.well-known/openid-configuration
    - uri: /.well-known/data-space-configuration
      upstream:
        nodes:
          dsconfig:3002: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /.well-known/data-space-configuration/data-space-configuration.json
        response-rewrite:
          headers:
            set:
              content-type: application/json
    - uri: /*
      host: mp-data-service.127.0.0.1.nip.io
      upstream:
        nodes:
          data-service-scorpio:9090: 1
        type: roundrobin
      plugins:
        openid-connect:
          bearer_only: true
          use_jwks: true
          client_id: data-service
          client_secret: unused
          ssl_verify: false
          discovery: http://verifier:3000/services/data-service/.well-known/openid-configuration
        opa:
          host: "http://localhost:8181"
          policy: policy/main
          with_body: true
    - uri: /.well-known/openid-configuration
      host: mp-tmf-api.127.0.0.1.nip.io
      upstream:
        nodes:
          verifier:3000: 1
        type: roundrobin
      plugins:
        proxy-rewrite:
          uri: /services/tmf-api/.well-known/openid-configuration
    - uri: /*
      host: mp-tmf-api.127.0.0.1.nip.io
      upstream:
        nodes:
          tm-forum-api:8080: 1
        type: roundrobin
      plugins:
        openid-connect:
          bearer_only: true
          use_jwks: true
          client_id: contract-management
          client_secret: unused
          ssl_verify: false
          discovery: http://verifier:3000/services/tmf-api/.well-known/openid-configuration
        opa:
          host: "http://localhost:8181"
          policy: policy/main
          with_body: true
dss:
  enabled: true
  keystores:
    store.jks: /u3+7QAAAAIAAAACAAAAAgANdGVzdC1rZXlzdG9yZQAAAZUZf4y3AAVYLjUwOQAABdgwggXUMIIDvKADAgECAgEBMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYDVQQGEwJERTEPMA0GA1UECAwGQmVybGluMQ8wDQYDVQQHDAZCZXJsaW4xEjAQBgNVBAoMCUZJV0FSRSBDQTESMBAGA1UEAwwJRklXQVJFLUNBMRwwGgYJKoZIhvcNAQkBFg1jYUBmaXdhcmUub3JnMQswCQYDVQQFEwIwMTAeFw0yNTAyMTgxNDM5MDJaFw0zNTAyMTYxNDM5MDJaMIGCMQswCQYDVQQGEwJERTEPMA0GA1UECAwGQmVybGluMQ8wDQYDVQQHDAZCZXJsaW4xEjAQBgNVBAoMCUZJV0FSRSBDQTESMBAGA1UEAwwJRklXQVJFLUNBMRwwGgYJKoZIhvcNAQkBFg1jYUBmaXdhcmUub3JnMQswCQYDVQQFEwIwMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALVC4267JFMrWle2L7lVqOK7fhFnWr2QnAYP3dBgheIrxSnGRR+iwv5Re/zrgMNb7Jv7yiUNQJV33mRk4i2sKfc6i/i7R8yh78T3GNYWUMvi/KwSKDkFvhJdy+xfSzVAZT1Adq9oRQA3VeOdkLQoyrFOEUCLVN1hIhQiFVn4TUGiUdmv9f82W5xdEd2xa2ndGb/SdvyOIb/nSFiMMyO1dZetOl5Jdv5M5SgpG/oYSbxRfLoY6Zne+sKFDRLo6CqunXCIggBLdNbfSeeSaEzmS4FsU7nXwbS/WBYFwsI2gBh76MH5o+8uMrEIJaeCCYukN7siv5PUngzZIsHv93bLTO60eu/RUsqvDtzPcab168+zq+GzA3B8tvTpQpr8HUmIVNbsYRuLQwuMIM3Um4qUJDHwTa5F6I6pRJDxS95WmWiNr9602YfAnHBSSZbFIsHRV2bqhB+DAc0joVEFAJZNgXP42FE1185d1DWheqr9N9qznzbwtLQZTkASm0dC5hS3IZ+kEDOMH4Y3zzau6raykuDAxWNhQazHEepu6Q0PK8/7OCpm8NrXvQOtfAZesQgW2+mulZnUJA3shZVh8i/p0y5nVI4xkKJwgUYZmWMVYSHm90SSIteplx9xJkhUMYOvnJWcnBQkqnISA4HLifhDpQZNhyYv2Yvbf0Nb5+AAR3IBAgMBAAGjUzBRMB0GA1UdDgQWBBTEOxISZ72nXv3z2csZOyERZsnapzAfBgNVHSMEGDAWgBTEOxISZ72nXv3z2csZOyERZsnapzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCe6iL1s19M5UDVLn5ipwZDudBNOcYXM8eqF5VIFowEWhajeJHGRZnsj+ZSXHLdJRq/j11k02XV037pmuuRV5J9n/tFr3PK7bJ3bONz3aZVCxdgV5Zyx0P86PEmXRAf0LdWjM9MDBBD2/Fdu07LYs1dxBKnhu/TcmG1iSGkKviWSwFtaFaxDHJ7i+yJZlv5Kq+jQ4x9eX1DurCLWi53qfot8m0/SchtMKtICl5w8QcQbHpFWDi3ZvzEO5V7ySNHemR+wh4SB4ck2ByoeqbgUs1OrXEPFfXkrUwweZwLf/rGz0gUNPkN4cgDqdxO09/evvKvfxIOyUAw9XV8WAvT7YSXWNU6AslgsCn9KlkRncXszGLbBGsf1VNiwMXEFJzZB+w+pGtOaynS7zwVwsJJMwaNgQ3yU1jDWfUuzIU1DweiLTGoJ08IHsRAWO4UnpBlYHIWJW6gV0Sy5fL7udfDV9WBAdVQX3Ez4ul4YPEAmGoX+z9mricwU2Cnv97TDIOSK33GDUsm0oFf6F3osODWxdWCXGg4VGziqukjMmoV9tiAsUZYdUEvWQBjx+dsXbaYO47RnakuF7QK3lRWmy+EC3NR+sLk/Mraydu5ctuCjPGc/ml+bamR1kVYhyftDbl0zLYij+p0JIoSjzyM1xjBlVTbBRTQs3YKetaTxdDjjEmr/wAAAAIADGludGVybWVkaWF0ZQAAAZUZf41uAAVYLjUwOQAABcwwggXIMIIDsKADAgECAgEBMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYDVQQGEwJERTEPMA0GA1UECAwGQmVybGluMQ8wDQYDVQQHDAZCZXJsaW4xEjAQBgNVBAoMCUZJV0FSRSBDQTESMBAGA1UEAwwJRklXQVJFLUNBMRwwGgYJKoZIhvcNAQkBFg1jYUBmaXdhcmUub3JnMQswCQYDVQQFEwIwMTAeFw0yNTAyMTgxNDM5MDJaFw0zMjA1MjIxNDM5MDJaMGQxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xEjAQBgNVBAoMCUZJV0FSRSBDQTESMBAGA1UEAwwJRklXQVJFLUNBMRwwGgYJKoZIhvcNAQkBFg1jYUBmaXdhcmUub3JnMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkgZXUYS9pcGJQQW4LPltoRzBFN5S1sefUZ0+GcEmA6SrC4js6Z8kmwmIo4sadkbqKmMYcGQVVs560fB9DHfOMyvnr1hpea479KTk8tjcIDz9zBFnvtq8YD4e9C73uiEgIfINMXjgvPqSuOeIAk/fPHX/N9m2KDNuRGB/ubSWSIombOWG6XemD8GMNLGxBH7QKd47wF4l/j5fXzC9HS/CBKTey6IUOaet3YwShC0WrHARy5LiH2tIwyKf/BgA/cLz7IT5Fc887n1nH/e3/L6db2ScBhf7sDQ+ZDiUiDxaBmBPkbSsOsQn5tOhxLSoIvfoko9svc9KfkMoRtzCxPYeU7qgkGyuI9betvA7zQsl9NrpeVd4HJFg6eAew2k+H9PZy7GbyoqOzqE1zsy8YykW+Purh0YGlK+WMC+MYRrk9HVialTz7hKA7iH4zuugz1sg//fmAteeXn4xPcTKxucToThIzh5e/kCMPCSBqIlVBb32GyDMaeNI3ELg6I/zbO02rjvhxwtTbQGGiPxsaqsNv++p9yvFvXTvepv3Dpqx44/OB3YM22/mYD/XDsmed5QL7HUuKya6+aVPttO+B5N3oVR4TF1xL/BJdMrNWkk8c2HJDVmVujAOFqfxxcJwYo2Kl2Vg3pIkKpe2YSPGfe/IFaK9xO15SkwmydAA8JTVLDcCAwEAAaNmMGQwHQYDVR0OBBYEFKXxVPwaFuhiJfjGN3OZmw4ApzhRMB8GA1UdIwQYMBaAFMQ7EhJnvade/fPZyxk7IRFmydqnMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQBz1YZbcMvU1cQXMdc0VN5z34UpRxDK7g56Uu+cswONc0YXZleOi2NbDYe6FC/9HIGhL5QloWwU9Md+oFO7uGJSaqPtYGqRVGKIvE+HqRE2JeoN6+gMJj0yq+2Pu1kyzLD1hvdHYosaWWRVOEOImgZKWpgqZIgAzbCPl3Ytkp3uzaY5zG+XbSkbWtZx3jrySRV2nweK0+yzwGw3c8XmrfG/3OeLuJFEmhAJ9GQgBpF0PEfS1gAIByFcc1wxbw4CO+KGX964o3Dgdxal1QCXuTWKfQy+x2bhv8+AFSXZhAzhHcOIDV2LJVXthbZsT6pfcatwX/otVKBqcdVghwbgiw5jVHBVWFUwuMjUycFVv/W4Cu9NPMQpmzJu5sswYBYWKFM32NNL0utjkbzdffvJd8LFdU8najSmM4uZZ/2/D0N+sdiR/7m2AdwPk+6GFI9s2cn9ATxTxBm+vz+DXBMTar4XWzs0pOVbelY9FtDdGiRXHZXlzq1e9xf3WfmLlzzUXjibJtiMThyL977xCa3y/nTuPlmdY8QIdw9FvSHJAKtDsKVaZYMImxTTVDlQtQIQYeFdB96G6mwrc1ie106h/iRjAuVEm16IzeJwceVVM+b2zz00mFqi8xXSILWqgShlDwrtulVdqCxEzayAiZbxYkDnpPMeRUMWsM3BleOEdMc3jnCS7njzal+oKR9Zhi0bx121vOFX
  trust:
    stores:
      - path: /keystores/store.jks
        type: jks
        password: password
  deployment:
    additionalContainers:
      - name: crl-provider-static
        imagePullPolicy: Always
        image: "lipanski/docker-static-website:2.1.0"
        volumeMounts:
          - name: crl-provider-json
            mountPath: /home/static/crl.pem
            subPath: crl.pem
    additionalVolumes:
      - name: crl-provider-json
        secret:
          secretName: crl-provider
  health:
    port: 8080
  crl:
    enabled: true
    secret:
      crl.pem: LS0tLS1CRUdJTiBYNTA5IENSTC0tLS0tCk1JSURuRENDQVlRQ0FRRXdEUVlKS29aSWh2Y05BUUVMQlFBd1pERUxNQWtHQTFVRUJoTUNSRVV4RHpBTkJnTlYKQkFnTUJrSmxjbXhwYmpFU01CQUdBMVVFQ2d3SlJrbFhRVkpGSUVOQk1SSXdFQVlEVlFRRERBbEdTVmRCVWtVdApRMEV4SERBYUJna3Foa2lHOXcwQkNRRVdEV05oUUdacGQyRnlaUzV2Y21jWERUSTFNREl4T0RFME16a3dNMW9YCkRUSTFNRE15TURFME16a3dNMW93SnpBbEFoUWxuU1ZPTE83SThRK2VKWFErcDlsZnZhN3B3eGNOTWpVd01qRTQKTVRRek9UQXpXcUNCd2pDQnZ6Q0Jyd1lEVlIwakJJR25NSUdrZ0JTbDhWVDhHaGJvWWlYNHhqZHptWnNPQUtjNApVYUdCaUtTQmhUQ0JnakVMTUFrR0ExVUVCaE1DUkVVeER6QU5CZ05WQkFnTUJrSmxjbXhwYmpFUE1BMEdBMVVFCkJ3d0dRbVZ5YkdsdU1SSXdFQVlEVlFRS0RBbEdTVmRCVWtVZ1EwRXhFakFRQmdOVkJBTU1DVVpKVjBGU1JTMUQKUVRFY01Cb0dDU3FHU0liM0RRRUpBUllOWTJGQVptbDNZWEpsTG05eVp6RUxNQWtHQTFVRUJSTUNNREdDQVFFdwpDd1lEVlIwVUJBUUNBaEFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDQVFCVmNaWEt2SWpPVGRMSnI5YUpRK1FrCmVRd2JjK0JyOHIzT0RVckQrWTNSNjBsV0lac3ZhU1ZsRm9aZ1RrUHJueHpGMWgyWVZrd0ZzamhOQTU3MzVnNVQKQVExemZ4aEdtSzFRZE91LzVMdms2UUljSmUvQkNiaWJYYVZJR2dKUE1lbFhyQ3RRYTBWbmszbWl2Nm1ZYStycAowbTZ6MzBxNDJBT0x5N0g3ZVJnd1Q5SjdGMkxtM0d2UHExa1dtVGpjUXZ4SjlOL1VoNjdNdXdpc1kvUCt6RXhPCmxpRVlRZE5RWXBhM0Zad3RLeXAvV2FPVndGRHBHbmd6bUZ3Z2VIN1hkV2EzTlFjVjFIc1FhN0RWV2hKNlRpZ1gKbzd1WVlzL08vZStFb0lXNVV6QmhxTVQwQ2JNSmpYOWRUcTVoanVVRlpIcE1peU1UMVdJVFFEejBUOThBUk9zWApmV1RFSzRndVQ5YTFseUN1NEdPSk9lU254VTd1aTRVNVFUNUpYUDM1S0diT0Q3cU4zY0I3MFQrWmVPaGx3TkV1CkRlZ2ZJeUI1RzRtbG9PTUhYN1pyeE5UaFk4MjB5ZUdXa1lwZi8zeTVHcytsem9zRGhlSU9YUy9FdjFmNEUwUHAKd083NkViK01NZG9sR2ZPVWtSc01HWGNoUWZHeTJ2T3RwNVFGQmwycU0vUDR3WnpUU1ZHYXJnT2VDNTZjTWpmTgpxUnVLcFExNDRmSnhjYmRLT0E1T2IrWnpKR0RhMnJkLzh6Z2JWbE9KbGprYnNLdXdJbFNja2dwcDVJdUhmK2VVCkQzUG9xU0lQQW9BNVJsUnd5czBna1BRdy9QUE9VazZqZXorRW91dkJsWS9RSnV6dWxPOWJlVVdyUkcweGJDUlIKRTA1OFF3U04vWC9qV3NLZy9wOU8yUT09Ci0tLS0tRU5EIFg1MDkgQ1JMLS0tLS0K
vcverifier:
  ingress:
    enabled: true
    hosts:
      - host: provider-verifier.127.0.0.1.nip.io
        paths:
          - "/"
  deployment:
    verifier:
      tirAddress: http://tir.127.0.0.1.nip.io:8080/
      did: did:web:mp-operation.org
    server:
      host: http://provider-verifier.127.0.0.1.nip.io:8080
    configRepo:
      configEndpoint: http://credentials-config-service:8080
    logging:
      level: DEBUG
    elsi:
      enabled: true
      validationEndpoint:
        host: http://dss:8080
        validationPath: /validateSignature
        healthPath: /health/liveness
    alternativeConfig: /alternative-conf/server.yaml
    additionalVolumes:
      - name: did-material
        emptyDir: {}
      - name: alternative-conf
        emptyDir: {}
    additionalVolumeMounts:
      - name: alternative-conf
        mountPath: /alternative-conf
    initContainers:
      - name: get-did
        image: ubuntu
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            apt-get -y update; apt-get -y install wget; apt-get -y install gettext-base
            cd /did-material
            wget http://did-helper:3002/did-material/did.env
            export $(cat /did-material/did.env)
            cp /original-conf/server.yaml /alternative-conf/server.yaml
            envsubst < /alternative-conf/server.yaml
        volumeMounts:
          - name: did-material
            mountPath: /did-material
          - name: config-volume
            mountPath: /original-conf
          - name: alternative-conf
            mountPath: /alternative-conf
      - name: register-at-tir
        image: ubuntu
        command:
          - /bin/bash
        args:
          - -ec
          - |
            #!/bin/bash
            source /did-material/did.env
            apt-get -y update; apt-get -y install curl
            curl -X 'POST' 'http://tir.trust-anchor.svc.cluster.local:8080/issuer' -H 'Content-Type: application/json' -d "{\"did\": \"did:web:mp-operation.org\", \"credentials\": []}"
        volumeMounts:
          - name: did-material
            mountPath: /did-material
mysql:
  primary:
    persistence:
      enabled: false
  secondary:
    persistence:
      enabled: false
postgis:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
postgresql:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
did:
  enabled: true
  secret: issuance-secret
  serviceType: ClusterIP
  port: 3002
  cert:
    country: DE
    state: SAXONY
    locality: Dresden
    organization: M&P Operations Inc.
    commonName: www.mp-operation.org
  ingress:
    enabled: true
    host: did-provider.127.0.0.1.nip.io
dataSpaceConfig:
  enabled: true
  serviceType: ClusterIP
  port: 3002
  supportedModels:
    - "https://raw.githubusercontent.com/smart-data-models/dataModel.Consumption/master/ConsumptionPoint/schema.json"
    - "https://raw.githubusercontent.com/smart-data-models/dataModel.Consumption/master/ConsumptionCost/schema.json"
  supportedProtocols:
    - http
    - https
  authenticationProtocols:
    - oid4vp
scorpio:
  ingress:
    enabled: true
    # only to make it available for the test initialization
    hosts:
      - host: scorpio-provider.127.0.0.1.nip.io
        paths:
          - "/"
  ccs:
    defaultOidcScope:
      name: default
    oidcScopes:
      default:
        - type: UserCredential
          trustedParticipantsLists:
            - http://tir.trust-anchor.svc.cluster.local:8080
          trustedIssuersLists:
            - http://trusted-issuers-list:8080
      operator:
        - type: OperatorCredential
          trustedParticipantsLists:
            - http://tir.trust-anchor.svc.cluster.local:8080
          trustedIssuersLists:
            - http://trusted-issuers-list:8080
odrl-pap:
  additionalEnvVars:
    - name: GENERAL_ORGANIZATION_DID
      value: did:web:mp-operation.org
  deployment:
    command:
      - /bin/sh
    args:
      - -ec
      - |
        #!/bin/sh
        ./application -Dquarkus.http.host=0.0.0.0
  ingress:
    enabled: true
    hosts:
      - host: pap-provider.127.0.0.1.nip.io
        paths:
          - "/"
tm-forum-api:
  registration:
    ccs:
      defaultOidcScope:
        credentialType: UserCredential
        trustedParticipantsLists: http://tir.trust-anchor.svc.cluster.local:8080
  ingress:
    enabled: true
    hosts:
      - host: tm-forum-api.127.0.0.1.nip.io
        paths:
          - /
contract-management:
  til:
    credentialType: OperatorCredential
  services:
    ## Config for Trusted Issuers List
    trusted-issuers-list:
      ## URL of the Trusted Issuers List Service
      url: http://trusted-issuers-list:8080
trusted-issuers-list:
  # only open for clean up in the tests
  ingress:
    til:
      enabled: true
      hosts:
        - host: til-provider.127.0.0.1.nip.io
          paths:
            - /
rainbow:
  enabled: false
  db:
    url: postgresql
    user: postgres
    existingSecret: database-secret
    passwordKey: postgres-admin-password
